### ISSUE TITLE
Preferences xml erreur v0.2-beta

### ISSUE THREAD

**Issue by vincentbls** [loicdugay/synology-plex-auto-update#3]
Sortie/erreur standard :
Version de Plex supérieure à 1.24.2.4973 détectée
**cat: '/volume1/PlexMediaServer/AppData/Plex Media Server/Preferences.xmlcle': No such file or directory**
Version disponible : 1.24.2.4973
Version installée : 1.24.2.4973

**Comment by loicdugay** [comment]
Fixed in v.0.2.1-beta

**Comment by vincentbls** [comment]
Ca semble fonctionner, plus de message d'erreur. A voir lorsqu'une mise à jour sera disponible. Merci.
