### ISSUE TITLE
Eviter les mise à jour beta (plexpass) et avoir uniquement les MAJ stables

### ISSUE THREAD

**Issue by Cadkey** [loicdugay/synology-plex-auto-update#4]
Bonjour,
J'utilise votre derniere version sur DSM7.
Le script met à jour la derniere version de PMS, donc en version beta aujourd'hui 1.24.3.5033-757abe6b4.
Je voudrais n'installer que la version stable, non beta (plexpass=0) 1.24.2.4973-2b1b51db9
Comment indiquer cette variable dans votre script pour ne recevoir que les mise à jour stables svp
Merci

**Comment by Shkrum31** [comment]
Bonjour,
Il suffit de corriger le script en enlevant les paramètres indiqués dans l'url suivante : 
[`url=$(echo "https://plex.tv/api/downloads/5.json?channel=plexpass&X-Plex-Token=$token")`](https://github.com/loicdugay/synology-plex-auto-update/blob/a61b9f001269f8d3f4658294b3d2559a734cbeb8/plex_update.sh#L61)
Ce qui amène à :
`url=$(echo "https://plex.tv/api/downloads/5.json")`

**Comment by Cadkey** [comment]
Bonjour,
Mon post date de septembre 2021, la question est résolue depuis longtemps 😉

**Comment by Shkrum31** [comment]
J'imagine ! Je viens de proposer un pull request

**Comment by Cadkey** [comment]
Lol mdr.
